### ISSUE TITLE
SS 4.5.4 compatibility

### ISSUE THREAD

**Issue by georgehemmings** [MacLeanElectrical/servicestack-introspec#14]
Hey

Will you be upgrading this project to be compatible with SS 4.5.4? I can see there is a develop branch that is targeting 4.5.0.

**Comment by wwwlicious** [comment]
Hi George,

We are currently running IntroSpec 4.0.36 on an internal project with SS 4.5.4 without any issues. Is there something specific that breaks for you?

**Comment by georgehemmings** [comment]
Oh right cool, I'll give it a go.

I presumed you were matching SS version numbers, where they're all kept in lockstep.

**Comment by wwwlicious** [comment]
A fair assumption but we haven't needed to so far. We will probably only do this for major breaking changes or version bumps from SS unless there are valid reasons to do so like breaking contract changes in SS. 

Otherwise our packages tend to target a specific min version up to a major version bump. e.g. (>= 4.0.56 && < 5.0.0) for IntroSpec version 4.0.36.

**Comment by georgehemmings** [comment]
👍 good to know
